version: "3"
services:
   web:
      image: fulton/ara
      expose:
         - 8080
      environment:
         dblink: mongo:27017
         dbname: ara
         dbpassword: thepassword
         PORT: 8080
         BING: 92a4005e9ce94f8ea70bf62a3bd42bd9
         NLP: nlp:5000
      depends_on:
        - mongo
        - nlp
   mongo:
      image: mongo:latest
      container_name: mongo
      volumes:
         - test2-volume:/data/db

   mongoClientTemp:
      image: mongo:latest
      container_name: mongoClientTemp
      links:
         - mongo:mongo
      volumes:
         - ./init-skills.js:/data/mongostartup/init-skills.js
      command: mongo --host mongo < /data/mongostartup/init-skills.js 
      depends_on:
         - mongo
   nlp:
      image: fulton/ara-nlp
      expose: 
         - 5000
      ports:
         - 5000:5000
   nginx:
      restart: unless-stopped
      image: nginx:latest
      environment:
         WEB_SERVER_NAME: ${DOMAIN}
      ports:
         - 80:80
         - 443:443
      volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf
         - ./keys/conf:/etc/letsencrypt
         - ./keys/certbot/www:/var/www/certbot
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
      depends_on:
        - web
   certbot:
      image: certbot/certbot
      restart: unless-stopped
      volumes:
         - ./keys/conf:/etc/letsencrypt
         - ./keys/certbot/www:/var/www/certbot
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
   postgres:
      image: postgres
      volumes:
        - postgres_data1:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: ${DB_PASSWORD}
   keycloak:
      image: jboss/keycloak:10.0.0
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: ${DB_PASSWORD}
        DB_PORT: 8000
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
        
      ports:
        - 8000:8000
      depends_on:
        - postgres
volumes:
   test2-volume: 
   production-volume:
   postgres_data1:
