version: "3.0"
services:
        web:
                image: "fulton/ara-server"
                ports:
                        - 80:80
        auth:
                image: "jboss/keycloak"
                ports:
                        - 8080:8080
                enviroment:
                        - KEYCLOAK_USER=araadmin
                        - KEYCLOAK_PASSWORD=lol
        authbd:
                image: ""
                ports: 
                        -8000:8000
                volumes:
                        - database-data:/var/lib/postgresql/data/
        nlp:
                image: ""
                ports:
                        -5000:5000

