version: "3"
services:
   web:
      build: .
      ports:
         - "8080:8080"
      expose:
         - 8080
      environment:
         - dblink=aratest-gbnnv.azure.mongodb.net
         - dbname=ara
         - PORT=8080
         - BING=92a4005e9ce94f8ea70bf62a3bd42bd9


