version: "3"
services:
   web:
      image: fulton/ara
      ports:
         - 80:8080
      expose:
         - 8080
      environment:
         dblink: mongo:27017
         dbname: ara
         dbpassword: thepassword
         PORT: 8080
         BING: 92a4005e9ce94f8ea70bf62a3bd42bd9
         NLP: nlp:5000
      depends_on:
        - mongo
        - nlp
   mongo:
      image: mongo:latest
      container_name: mongo
      volumes:
         - production-volume1:/data/db

   mongoClientTemp:
      image: mongo:latest
      container_name: mongoClientTemp
      links:
         - mongo:mongo
      volumes:
         - ./init-skills.js:/data/mongostartup/init-skills.js
         - ./wait.sh:/wait.sh
      command: mongo --host mongo < /data/mongostartup/init-skills.js
      depends_on:
         - mongo
   nlp:
      image: fulton/ara-nlp
      expose: 
         - 5000
      ports:
         - 5000:5000
volumes:
   test2-volume: 
   production-volume1:
   postgres_data4:
