version: "3"
services:
   web:
      image: fulton/ara
      ports:
         - "80:8080"
      expose:
         - 8080
      environment:
         dblink: mongo:27017
         dbname: ara
         dbpassword: thepassword
         PORT: 8080
         BING: 92a4005e9ce94f8ea70bf62a3bd42bd9
         NLP: nlp:5000
      depends_on:
        - mongo
        - nlp
   mongo:
      image: mongo:latest
      container_name: mongo
      ports:
         - "27017:27017"
      volumes:
         - /app/hdp/mongo/data:/data/db

   mongoClientTemp:
      image: mongo:latest
      container_name: mongoClientTemp
      links:
         - mongo:mongo
      command: mongo --host mongo --eval  "db.getSiblingDB('ara').createUser({user:'ara', pwd:'thepassword', roles:[{role:'readWrite',db:'ara'}]});"
      depends_on:
         - mongo
   nlp:
      image: fulton/ara-nlp
      expose: 
         - 5000
      ports:
         - 5000:5000
volumes:
  data-volume:


