version: "3"
services:
   web:
      image: fulton/ara
      expose:
         - 8080
      environment:
         dblink: mongo:27017
         dbname: ara
         dbpassword: thepassword
         PORT: 8080
         BING: 92a4005e9ce94f8ea70bf62a3bd42bd9
         NLP: nlp:5000
      depends_on:
        - mongo
        - nlp
   mongo:
      image: mongo:latest
      container_name: mongo
      volumes:
         - test2-volume:/data/db

   mongoClientTemp:
      image: mongo:latest
      container_name: mongoClientTemp
      links:
         - mongo:mongo
      volumes:
         - ./init-skills.js:/data/mongostartup/init-skills.js
      command: mongo --host mongo < /data/mongostartup/init-skills.js 
      depends_on:
         - mongo
   nlp:
      image: fulton/ara-nlp
      expose: 
         - 5000
      ports:
         - 5000:5000
   nginx:
      image: nginx:latest
      ports:
         - 80:80
         - 443:443
      volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf
         - ./keys/certbot/www:/var/www/certbot
         - ./keys/cert.crt:/etc/nginx/ssl/cert.crt
         - ./keys/cert.key:/etc/nginx/ssl/cert.key
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
   certbot:
      image: certbot/certbot
      restart: unless-stopped
      volumes:
         - ./keys:/etc/letsencrypt
         - ./keys/certbot/www:/var/www/certbot
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
   test2-volume: 
   production-volume:


