version: "3"
services:
   web:
      image: fulton/ara
      ports:
         - "8080:8080"
      expose:
         - 8080
      environment:
         - dblink=db:27017
         - dbname=ara
         - dbpassword=thepassword
         - PORT=8080
         - BING=92a4005e9ce94f8ea70bf62a3bd42bd9
      depends_on:
        - db
   db:
      image: mongo
      expose:
         - "27017"
      environment:
         ME_CONFIG_MONGODB_ADMINUSERNAME: root
         ME_CONFIG_MONGODB_ADMINPASSWORD: BigSecurePassword
         MONGO_INITDB_DATABASE: ara
         MONGODB_USER: "ara"
         MONGODB_DATABASE: "ara"
         MONGODB_PASS: "thepassword"
      volumes:
         - data-volume:/data/db
volumes:
  data-volume:


